### ISSUE TITLE
Not warning about `.editor` selectors in keymaps

### ISSUE THREAD

**Issue by nathansobo** [atom/deprecation-cop#17]

**Comment by marshall007** [comment]
It looks like deprecated selectors in `~/.atom/styles.less` are also not reported.

**Comment by maxbrunsfeld** [comment]
@marshall007 can you open a separate issue for this? Currently, we make no effort to lint the user's own configuration: only packages. But it probably makes sense to warn individual users that their config will eventually stop working.
