### ISSUE TITLE
Add the ability to file an issue for deprecated selectors

### ISSUE THREAD

**Issue by benogle** [atom/deprecation-cop#23]
_From @alex on January 22, 2015 20:14_

Deprecated Javascript APIs have an awesome ability to just file a bug for them automatically, it'd be great if that were also possible for deprecated selectors.

_Copied from original issue: atom/atom#5221_

**Comment by benogle** [comment]
@alex thanks for the report!

**Comment by alex** [comment]
@benogle Happily! (Can I say that a one-click to file an issue on using deprecated stuff is amazing)

**Comment by benogle** [comment]
:+1:
