### ISSUE TITLE
Text is huge with one-dark-ui

### ISSUE THREAD

**Issue by postcasio** [atom/deprecation-cop#35]
Not 100% sure if this belongs here or on one-dark-ui. The `deprecation-message` has `font-size: 3em` which I think is causing problems with the recent font size changes.

cc @simurai 

![screen shot 2015-04-10 at 17 11 47](https://cloud.githubusercontent.com/assets/1759837/7091854/120ae3c6-dfa5-11e4-9bea-6900b4705b02.png)

**Comment by thomasjo** [comment]
Duplicate of https://github.com/atom/deprecation-cop/issues/34.

**Comment by postcasio** [comment]
Whoops, my bad



—
