### ISSUE TITLE
Incorrect attribution of deprecated calls to atom core or a core package

### ISSUE THREAD

**Issue by izuzak** [atom/deprecation-cop#36]
I noticed this while I was updating one of my packages to 1.0 APIs:

![screen shot 2015-04-15 at 16 29 57](https://cloud.githubusercontent.com/assets/38924/7201317/2523fee6-e506-11e4-9a77-f8969c6dd074.png)

Deprecation cop is saying that Atom is the problem here, but it's not -- it's a package.

A similar issue was reported here: https://github.com/atom/status-bar/issues/69

In that issue, @kevinsawicki mentioned (referring to the call stack):

> atom/grim#4 started limiting the depth to 3 

That status-bar deprecation issue was fixed in the status-bar package itself by @maxbrunsfeld, but I'm guessing there are more incorrect attributions like these, e.g. https://github.com/atom/atom/issues/6310. 

Would it be possible to apply a wider/global fix to this (maybe by increasing the depth to 4-5 in Grim? Would that catch most/all problems?)? That would help users create deprecation issues in the right place and reduce issue triage work around these issues. :sparkles:

cc @nathansobo because you worked on the Grim pull request referenced above :point_up:. Also cc @atom/issue-triage.

**Comment by kevinsawicki** [comment]
> maybe by increasing the depth to 4-5 in Grim? 

I think this is the right first step, 5 sounds good, do you want to open a PR for this?

**Comment by izuzak** [comment]
> I think this is the right first step, 5 sounds good, do you want to open a PR for this?

Sure :+1: Here it is: https://github.com/atom/grim/pull/5.

I just played with this locally and it definitely improves things. 

Example before (attributed to atom core):

![screen shot 2015-04-21 at 09 05 22](https://cloud.githubusercontent.com/assets/38924/7247228/8d01c94a-e807-11e4-96c9-b8b10f5dca56.png)

Example after (attributed to pdf-view):

![screen shot 2015-04-21 at 09 05 33](https://cloud.githubusercontent.com/assets/38924/7247232/9a953cf4-e807-11e4-8492-ae52081dcd37.png)

However, I'm still seeing cases where deprecation cop is not attributing deprecated calls correctly regardless of the stack depth. Here's an example with stack depth 20 (more than the total depth of the call):

![screen shot 2015-04-21 at 09 09 25](https://cloud.githubusercontent.com/assets/38924/7247256/dfa0d65a-e807-11e4-9f07-37ec94ee6c9e.png)

Those two deprecations should be attributed to a package as well. I suspect that this is a different problem, though, since the call stack doesn't include anything from the package. The related `Grim.deprecate` calls are [here](https://github.com/atom/atom/blob/4fb59af3cc5205de3f3a20416d83d102dcfe1cb1/src/pane-view.coffee#L122) and [here](https://github.com/atom/atom/blob/4fb59af3cc5205de3f3a20416d83d102dcfe1cb1/src/pane-view.coffee#L131).

**Comment by maxbrunsfeld** [comment]
>  The call stack doesn't include anything from the package. The related Grim.deprecate calls are here and here.

I think we should remove those two `Grim` calls, and replace them with preemptive checks in [`Workspace::addOpener`](https://github.com/atom/atom/blob/4fb59af3cc5205de3f3a20416d83d102dcfe1cb1/src/workspace.coffee#L487), like we did for the deprecated `::getUri` method. That way, the stack trace will contain the line from the package where the opener callback is registered.

**Comment by kevinsawicki** [comment]
> I think we should remove those two Grim calls, and replace them with preemptive checks in Workspace::addOpener, like we did for the deprecated ::getUri method. That way, the stack trace will contain the line from the package where the opener callback is registered.

:+1:

**Comment by izuzak** [comment]
It seems that another common source of incorrect attributions is [this deprecation call](https://github.com/atom/atom/blob/3e993ca9e6b9a12bc175231ab1a05cf787fdfb9e/src/package.coffee#L469-L476) after checking if the package switched to the new activationCommands from activationEvents.

For example, here's what I see after installing [redacted](https://github.com/ymendel/atom-redacted):

![screen shot 2015-04-23 at 17 08 12](https://cloud.githubusercontent.com/assets/38924/7300241/5a7d5c84-e9db-11e4-93d2-c01046a71fca.png)

It doesn't seem to be related to the stack depth -- I tried increasing it to 20 (from 5) and it didn't help.

I'd like to work on improving this but would need a pointer on where to start. @maxbrunsfeld @kevinsawicki :pray: :smile:

**Comment by maxbrunsfeld** [comment]
I think we could solve this similarly to what we did [here](https://github.com/atom/atom/blob/6e074b3695a532585fff6f6c97ae4ec3b535f4a5/src/workspace.coffee#L488) - pass a `packageName` parameter to `Grim::deprecate`.

**Comment by maxbrunsfeld** [comment]
Here's another one of these issues: https://github.com/atom/settings-view/issues/476

Looks like to solve that, we need to do the same thing for [this call](https://github.com/atom/atom/blob/3e993ca9e6b9a12bc175231ab1a05cf787fdfb9e/src/package.coffee#L164) (in the same file).

**Comment by izuzak** [comment]
:metal: Thanks, @maxbrunsfeld -- I'll try that and open a pull request.

**Comment by izuzak** [comment]
Closing this since I think we've handled all problems that have been reported. If anything new pops up -- please feel free to reopen and add more details.
