### ISSUE TITLE
Wrong indentation in deprecation cop

### ISSUE THREAD

**Issue by izuzak** [atom/deprecation-cop#49]
_From @goffreder on May 20, 2015 7:34_

In the list of the "Deprecated selectors", if you expand one row, the next one becomes indented as it's part of the row above. See screenshot.

![schermata 2015-05-20 alle 09 33 47](https://cloud.githubusercontent.com/assets/156642/7720996/722c5896-fed3-11e4-9932-13d86aa7e9af.png)

_Copied from original issue: atom/atom#6863_

**Comment by izuzak** [comment]
@goffreder I'm having trouble reproducing this:

![screen shot 2015-05-20 at 09 42 21](https://cloud.githubusercontent.com/assets/38924/7721121/ae46e76e-fed4-11e4-80c5-a9049273a58e.png)

Which version of Atom are you using exactly and which themes? And if you run Atom with `atom --safe .`, and then open Deprecation Cop -- are the deprecations for your keymap.cson and styles.less file still incorrectly indented?

**Comment by goffreder** [comment]
I'm running Atom 0.200.0 on OSX 10.10.3. I'm using the Seti theme, version 0.7.1.

I ran atom in safe mode but I get the same issue...

![schermata 2015-05-20 alle 09 54 03](https://cloud.githubusercontent.com/assets/156642/7721257/691235a2-fed6-11e4-82d7-c8dfb465e841.png)

**Comment by izuzak** [comment]
@goffreder Thanks for confirming -- I can reproduce this with the Atom Dark theme as well, but can't reproduce it with the default One Dark theme. 

I'm gonna call @simurai for backup here :phone: since this might require some fine tuning of pixels :art:. I think the warning icons are causing problems here in some themes -- their position and height makes them cross to the other line vertically so subsequent lines are indented to the right of the icon of the previous line.

**Comment by simurai** [comment]
I can't reproduce it and oddly, when I add some old classes to my `styles.less`. I can see the `your local styles.less file`, but it's empty.

![screen shot 2015-05-20 at 6 06 11 pm](https://cloud.githubusercontent.com/assets/378023/7722432/11ef0d5a-ff1b-11e4-90fa-4adba86f3cde.png)

**Comment by izuzak** [comment]
@simurai Are you perhaps not using the latest version of Atom? That problem with the empty list was a bug which was fixed recently: https://github.com/atom/deprecation-cop/pull/48

**Comment by simurai** [comment]
@izuzak Yep, was on a different branch. Should be fixed in the next release.

**Comment by izuzak** [comment]
:heart_decoration: @simurai
