### ISSUE TITLE
'Check for Updates' button misaligned visually

### ISSUE THREAD

**Issue by emcek** [atom/deprecation-cop#60]
![image](https://cloud.githubusercontent.com/assets/475312/8648243/57095aee-295f-11e5-86dd-bbd8f3cd7324.png)

Button was added in: https://github.com/atom/deprecation-cop/commit/01459698b21f1c6da8536de74ebf3dc9c155e499

**Comment by lee-dohm** [comment]
Yes, this was an intentional change. This is so that if you discover a package you're running has active deprecations, you can check for updates to see if they are resolved.

**Comment by emcek** [comment]
I don't mind button itself, but its position is a bit odd.

**Comment by lee-dohm** [comment]
Ah ok. Thanks for clarifying.

@simurai, can you take a look?

**Comment by izuzak** [comment]
There's already a PR to fix this: https://github.com/atom/deprecation-cop/pull/59
