### ISSUE TITLE
Only show status-bar tile in dev mode?

### ISSUE THREAD

**Issue by mnquintana** [atom/deprecation-cop#63]
Now that the deprecopalypse has come and gone, do we still need to display the deprecation warning in the status bar in regular mode windows? I've been thinking lately that it might help reduce noise, since the deprecation warnings are generally only of use to package developers, and especially now that [other packages are beginning to use the deprecation API for their own purposes.](https://github.com/atom-community/linter/pull/676) My suggestion would be to only show deprecation warnings in the status bar in dev mode windows.

**Comment by 50Wliu** [comment]
Refs atom/atom#6945.

**Comment by thomasjo** [comment]
My initial reaction is agreement. I think it makes perfect sense to make deprecation-cop slightly less obtrusive in "regular mode".

**Comment by steelbrain** [comment]
I guess I am a little too late here but I am :-1:  on this, 'cause this allowed us to update our public/linter API with ease, and we could expect people to upgrade to it when we push a release, sadly, people don't see it anymore, which means that we'll have to re-invent the deprecation cop wheel. 'cause it's critically important to let people know that we are removing something.
Besides, if someone doesn't like it, they can always disable the package, most of the people don't wanna disable it and they want to know what's working/broken.
