### ISSUE TITLE
Make deprecations dismissable

### ISSUE THREAD

**Issue by lee-dohm** [atom/deprecation-cop#77]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When a deprecation has been reported, people other than the developer of the packages in question would like to be able to dismiss deprecations so they aren't constantly reminded of things they have little control over.

### Steps to Reproduce

1. Launch Atom
2. Click the "X deprecations" message in the status bar
3. Select a deprecation that has already been reported to the package's repository
4. Click the "Dismiss" button associated with that deprecation

**Expected behavior:** The deprecation is removed for that session and for all future sessions

**Actual behavior:** No "Dismiss" button available

### Versions

```
Atom    : 1.15.0-dev-82741c7ca
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

* https://discuss.atom.io/t/why-do-deprecation-messages-stick-around-on-plugin-code/38407

**Comment by Down10** [comment]
Either this, or else perhaps a setting to hide the notification that appears in the bottom bar.

**Comment by lee-dohm** [comment]
I reviewed this with the development team and they agree that it would be a nice option to have. On the other hand, this is not something that we will get the chance to work on any time soon. Because we treat the open issues list as our backlog of what we will be working on, I'm going to close this.

We would be open to accepting a well-crafted pull request that implements such a feature, so I'll mark this with `help-wanted`.
